easy_admin:
    site_name: 'Administration'
    formats:
        date:     'd/m/Y'
        time:     'H\hi'
        datetime: 'd/m/Y \à H\hi'

    design:
        menu:
            - { label: 'Invités' }
            - { entity: 'GuestWaiting', icon: 'user-tie', label: 'Invités en attente' }
            - { entity: 'GuestWhoReplied', icon: 'user-tie', label: 'Invités ayant répondus' }
            - { label: 'Liste de mariage' }
            - { entity: 'ListItem', icon: 'tasks', label: 'Configuration' }
            - { entity: 'Gift', icon: 'gifts', label: 'Cadeaux' }
            - { label: 'Réglages' }
            - { entity: 'User', icon: 'user-circle', label: 'Utilisateurs' }
            - { entity: 'TextBlock', icon: 'edit', label: 'Blocs de texte' }
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

    entities:
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                fields: 
                    - { property: 'username', label: 'Nom' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'enabled', label: 'Activé' }
                    - { property: 'lastLogin', label: 'Dernière connexion' }
                    - { property: 'roles', label: 'Rôles' }
                    - { property: 'guests', label: 'Invités' }
                actions: 
                    - { name: 'emailWhenActivated', label: "Email d'activation" }
            search:
                fields: ['username', 'email', 'enabled', 'lastLogin']
            form:
                fields:
                    - { property: 'username', label: 'Nom' }
                    - { property: 'email', label: 'E-mail' }
                    - { property: 'enabled', label: 'Activé' }
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', label: 'Mot de passe', type: 'text', type_options: { required: false } }
                    - { property: 'roles', label: 'Rôles', type: 'choice', type_options: { multiple: true, choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' } } }
                    - { property: 'guests', label: 'Invités', type_options: { by_reference: false } }

        TextBlock:
            class: App\Entity\TextBlock
            label: 'Blocs de texte'
            list:
                fields: 
                    - { property: 'name', label: 'Nom' }
                    - { property: 'content', label: 'Contenu' }
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'content', label: 'Contenu', type: 'fos_ckeditor', type_options: { config_name: 'config_with_uploadable_images' } }

        ListItem:
            class: App\Entity\ListItem
            label: 'Eléments de la liste'
            list:
                fields: 
                    - { property: 'ordering', label: 'Etape n°' }
                    - { property: 'title', label: 'Titre' }
                    - { property: 'price', label: 'Prix' }
                    - { property: 'link', label: 'Lien', type: 'url' }
                    - { property: 'imageName', label: 'Image', type: 'image', base_path: '%path.images.listItem%' }
                    - { property: 'gifted', label: 'Financé', type: 'boolean' }
                    - { property: 'lastEditedAt', label: 'Dernière modif.' }
                sort: 'ordering'
            form:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'price', label: 'Prix' }
                    - { property: 'link', label: 'Lien' }
                    - { property: 'gifted', label: 'Financé' }
                    - { property: 'splittable', label: 'Divisible' }
                    - { property: 'latitude', label: 'Latitude' }
                    - { property: 'longitude', label: 'Longitude' }
                    - { property: 'ordering', label: 'Etape n°' }
                    - { property: 'imageFile', label: 'Image', type: 'vich_image', base_path: '%path.images.listItem%' }

        Gift:
            class: App\Entity\Gift
            label: 'Cadeaux'
            list:
                fields: 
                    - { property: 'giver', label: 'Mécène' }
                    - { property: 'listItem', label: 'Cadeau' }
                    - { property: 'amount', label: 'Montant' }
                    - { property: 'message', label: 'Message' }
                    - { property: 'createdAt', label: 'Enregistré le' }
                sort: 'createdAt'
            form:
                fields:
                    - { property: 'giver', label: 'Mécène' }
                    - { property: 'listItem', label: 'Cadeau' }
                    - { property: 'amount', label: 'Montant' }
                    - { property: 'message', label: 'Message' }

        GuestWaiting:
            class: App\Entity\Guest
            label: 'Invités'
            list:
                fields:
                    - { property: 'name', label: 'Nom' }
                sort: 'name'
                dql_filter: 'entity.answeredAt is null'
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { type: 'section', label: '' }
                    - { property: 'answered', label: 'Remplir le formulaire de réponse à la place de l''invité ?', type: 'checkbox' }
                    - { property: 'attendCeremony', label: 'Participe à la cérémonie'}
                    - { property: 'attendMeal', label: 'Participe au repas'}
                    - { property: 'attendBrunch', label: 'Participe au brunch'}
                    - { property: 'veggie', label: 'Végétarien.ne'}
                    - { property: 'specialDiet', label: 'Régime alimentaire spécial'}

        GuestWhoReplied:
            class: App\Entity\Guest
            label: 'Invités'
            list:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'answeredAt', label: 'Date de la réponse' }
                    - { property: 'attendCeremony', label: 'Cérémonie' }
                    - { property: 'attendMeal', label: 'Repas' }
                    - { property: 'attendBrunch', label: 'Brunch' }
                    - { property: 'veggie', label: 'Végétarien.ne'}
                    - { property: 'specialDiet', label: 'Régime'}
                sort: 'answeredAt'
                dql_filter: 'entity.answeredAt is not null'
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'attendCeremony', label: 'Participe à la cérémonie'}
                    - { property: 'attendMeal', label: 'Participe au repas'}
                    - { property: 'attendBrunch', label: 'Participe au brunch'}
                    - { property: 'veggie', label: 'Végétarien.ne'}
                    - { property: 'specialDiet', label: 'Régime alimentaire spécial'}
