# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    input_sync: true
    configs:
        config_with_uploadable_images:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            toolbar: full

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
